/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */

  mySidebar: [
    {
      type: 'category',
      label: '概览',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'general/gettingStarted',
          label: '介绍'
        },
        // {
        //   type: 'doc',
        //   id: 'general/gadget',
        //   label: '在首页体验 Baitech'
        // },
        {
          type: 'doc',
          id: 'general/architecture',
          label: 'Baitech 架构'
        },
        {
          type: 'doc',
          id: 'general/pinningWithApi',
          label: 'API 认证机制'
        },
        {
          type: 'doc',
          id: 'general/faq',
          label: 'FAQ'
        },
      ]
    },
    {
      type: 'category',
      label: 'Baitech API',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'api/gatewayList',
          label: '获取网关列表'
        },
        {
          type: 'doc',
          id: 'api/upload',
          label: '上传文件或文件夹 (Upload)'
        },
        {
          type: 'doc',
          id: 'api/pin',
          label: '存储 (Pin)'
        }
      ]
    },
    {
      type: 'doc',
      id: 'pinningServicesApi',
      label: 'IPFS 远端存储服务 API'
    }
  ]
};
