name: Prod Release to GHCR

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: data-map
        id: data-map
        run: |
          echo '::set-output name=DATA_MAP::{"refs/heads/main":"baitech-docs"}'

      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DECOO_PAT }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/decooio/${{ fromJSON(steps.data-map.outputs.DATA_MAP)[github.ref] }}:latest
